### ISSUE TITLE
invalid cache created when including inline css 

### ISSUE THREAD

**Issue by narirou** [pug-php/pug#214] opened 2018-12-18 13:38 UTC
Hello,

When creating a cache with the following code by `cacheDirectory` method:
```pug
//- test.pug
doctype html

html
    head
        style(amp-custom)
            include ./test.css
    body
```
```css
// test.css
.test-class { color: red; }
```

We assumed that caches will be created including css file according to the following documents
https://www.phug-lang.com/#including-plain-text

But cache file(php) created without css, like this:
```php
<!-- ..... -->
<!DOCTYPE html><html><head><style<?= (is_bool($_pug_temp = $pugModule['Phug\\Formatter\\Format\\HtmlFormat::attributes_assignment'](array(  ), ['amp-custom' => true])) ? var_export($_pug_temp, true) : $_pug_temp) ?>></style></head><body></body></html>
```
And an error will occur when displaying this file using `Phug\Optimiser::displayFile`.

Thanks!

**Comment by kylekatarnls** [comment] 2018-12-19 06:18
I can't reproduce it, when I run this, I get the  **test.css** content inside the cache file.

What is you Pug-php/Phug version and what PHP code do you use to render/display the pug file?

**Comment by narirou** [comment] 2018-12-21 09:58
We will prepare the environment where problem occurs. Thanks.

**Comment by kylekatarnls** [comment] 2019-01-07 09:04
I close this for now, I will reopen if you can provide a minimal test case to reproduce the bug.

Thanks.

**Closed as completed by kylekatarnls** 2019-01-07 09:04 UTC
